include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/build/**"
    - "**/*.mocks.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Anda bisa menonaktifkan aturan spesifik jika sangat mengganggu
    # avoid_print: false
    # prefer_const_constructors: false
    # use_key_in_widget_constructors: false
