workflows:
  flutter-modular-workflow:
    name: Flutter Modular CI/CD
    instance_type: mac_mini_m2
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'final-project'
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies for all modules
        script: |
          flutter clean
          flutter pub get
          MODULES=("core" "db" "about" "movie" "tv" "watchlist")
          for module in "${MODULES[@]}"; do
            echo "Pub get in: modules/$module"
            cd "modules/$module"
            flutter pub get
            cd ../..
          done
      - name: Static Analysis
        script: |
          set -e
          echo "Analyzing project..."
          flutter analyze
          MODULES=("core" "db" "about" "movie" "tv" "watchlist")
          for module in "${MODULES[@]}"; do
            echo "Analyzing modules/$module"
            cd "modules/$module"
            flutter analyze
            cd ../..
          done
      - name: Run all tests (Unit & Integration)
        script: |
          set -e
          # Start iOS Simulator or Android Emulator if needed for Integration Test
          xcrun simctl list devices
          ID=$(xcrun simctl list devices | grep -E 'iPhone|iPad' | grep -v 'unavailable' | head -1 | awk -F '[()]' '{print $2}')
          if [ -z "$ID" ]; then
            echo "No simulator found"
          else
            echo "Booting simulator $ID"
            xcrun simctl boot $ID || true
          fi
          
          chmod +x run_tests.sh
          ./run_tests.sh
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - sedika.email@gmail.com
        notify:
          success: true
          failure: true
