// Mocks generated by Mockito 5.4.6 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:convert' as _i35;
import 'dart:typed_data' as _i36;

import 'package:core/core.dart' as _i17;
import 'package:dartz/dartz.dart' as _i2;
import 'package:db/database_helper.dart' as _i23;
import 'package:flutter_bloc/flutter_bloc.dart' as _i32;
import 'package:http/http.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i34;
import 'package:movie/data/models/movie_table.dart' as _i25;
import 'package:sqflite/sqflite.dart' as _i24;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i22;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i20;
import 'package:tv/data/models/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_model.dart' as _i21;
import 'package:tv/domain/entities/tv.dart' as _i18;
import 'package:tv/domain/entities/tv_detail.dart' as _i19;
import 'package:tv/domain/repos/tv_repository.dart' as _i4;
import 'package:tv/domain/usecases/get_on_the_air_tv.dart' as _i27;
import 'package:tv/domain/usecases/get_popular_tv.dart' as _i28;
import 'package:tv/domain/usecases/get_top_rated_tv.dart' as _i29;
import 'package:tv/domain/usecases/get_tv_detail.dart' as _i6;
import 'package:tv/domain/usecases/get_tv_recommendations.dart' as _i7;
import 'package:tv/domain/usecases/search_tv.dart' as _i30;
import 'package:tv/presentation/blocs/on_the_air_tv_bloc.dart' as _i12;
import 'package:tv/presentation/blocs/popular_tv_bloc.dart' as _i13;
import 'package:tv/presentation/blocs/top_rated_tv_bloc.dart' as _i14;
import 'package:tv/presentation/blocs/tv_detail_bloc.dart' as _i11;
import 'package:tv/presentation/blocs/tv_search_bloc.dart' as _i33;
import 'package:watchlist/data/models/watchlist_table.dart' as _i26;
import 'package:watchlist/domain/entities/watchlist.dart' as _i31;
import 'package:watchlist/domain/repos/watchlist_repository.dart' as _i5;
import 'package:watchlist/domain/usecases/get_watchlist_status.dart' as _i8;
import 'package:watchlist/domain/usecases/remove_watchlist.dart' as _i10;
import 'package:watchlist/domain/usecases/save_watchlist.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVDetailResponse_1 extends _i1.SmartFake
    implements _i3.TVDetailResponse {
  _FakeTVDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVRepository_2 extends _i1.SmartFake implements _i4.TVRepository {
  _FakeTVRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistRepository_3 extends _i1.SmartFake
    implements _i5.WatchlistRepository {
  _FakeWatchlistRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVDetail_4 extends _i1.SmartFake implements _i6.GetTVDetail {
  _FakeGetTVDetail_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVRecommendations_5 extends _i1.SmartFake
    implements _i7.GetTVRecommendations {
  _FakeGetTVRecommendations_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatus_6 extends _i1.SmartFake
    implements _i8.GetWatchListStatus {
  _FakeGetWatchListStatus_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlist_7 extends _i1.SmartFake implements _i9.SaveWatchlist {
  _FakeSaveWatchlist_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlist_8 extends _i1.SmartFake
    implements _i10.RemoveWatchlist {
  _FakeRemoveWatchlist_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVDetailState_9 extends _i1.SmartFake implements _i11.TVDetailState {
  _FakeTVDetailState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirTVState_10 extends _i1.SmartFake
    implements _i12.OnTheAirTVState {
  _FakeOnTheAirTVState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTVState_11 extends _i1.SmartFake
    implements _i13.PopularTVState {
  _FakePopularTVState_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTVState_12 extends _i1.SmartFake
    implements _i14.TopRatedTVState {
  _FakeTopRatedTVState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_13 extends _i1.SmartFake implements _i15.Response {
  _FakeResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_14 extends _i1.SmartFake
    implements _i15.StreamedResponse {
  _FakeStreamedResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRepository extends _i1.Mock implements _i4.TVRepository {
  MockTVRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> getOnTheAirTV() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTV, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#getOnTheAirTV, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> getPopularTV() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTV, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#getPopularTV, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> getTopRatedTV() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTV, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#getTopRatedTV, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, _i19.TVDetail>> getTVDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVDetail, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, _i19.TVDetail>>.value(
                  _FakeEither_0<_i17.Failure, _i19.TVDetail>(
                    this,
                    Invocation.method(#getTVDetail, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, _i19.TVDetail>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> getTVRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTVRecommendations, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#getTVRecommendations, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> searchTV(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTV, [query]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#searchTV, [query]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);
}

/// A class which mocks [TVRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRemoteDataSource extends _i1.Mock
    implements _i20.TVRemoteDataSource {
  MockTVRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<List<_i21.TVModel>> getOnTheAirTV() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTV, []),
            returnValue: _i16.Future<List<_i21.TVModel>>.value(
              <_i21.TVModel>[],
            ),
          )
          as _i16.Future<List<_i21.TVModel>>);

  @override
  _i16.Future<List<_i21.TVModel>> getPopularTV() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTV, []),
            returnValue: _i16.Future<List<_i21.TVModel>>.value(
              <_i21.TVModel>[],
            ),
          )
          as _i16.Future<List<_i21.TVModel>>);

  @override
  _i16.Future<List<_i21.TVModel>> getTopRatedTV() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTV, []),
            returnValue: _i16.Future<List<_i21.TVModel>>.value(
              <_i21.TVModel>[],
            ),
          )
          as _i16.Future<List<_i21.TVModel>>);

  @override
  _i16.Future<_i3.TVDetailResponse> getTVDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVDetail, [id]),
            returnValue: _i16.Future<_i3.TVDetailResponse>.value(
              _FakeTVDetailResponse_1(
                this,
                Invocation.method(#getTVDetail, [id]),
              ),
            ),
          )
          as _i16.Future<_i3.TVDetailResponse>);

  @override
  _i16.Future<List<_i21.TVModel>> getTVRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVRecommendations, [id]),
            returnValue: _i16.Future<List<_i21.TVModel>>.value(
              <_i21.TVModel>[],
            ),
          )
          as _i16.Future<List<_i21.TVModel>>);

  @override
  _i16.Future<List<_i21.TVModel>> searchTV(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTV, [query]),
            returnValue: _i16.Future<List<_i21.TVModel>>.value(
              <_i21.TVModel>[],
            ),
          )
          as _i16.Future<List<_i21.TVModel>>);
}

/// A class which mocks [TVLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVLocalDataSource extends _i1.Mock implements _i22.TVLocalDataSource {
  MockTVLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i23.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i24.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i16.Future<_i24.Database?>.value(),
          )
          as _i16.Future<_i24.Database?>);

  @override
  _i16.Future<void> insertCacheTransaction(
    List<_i25.MovieTable>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i16.Future<List<Map<String, dynamic>>>);

  @override
  _i16.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<int> insertWatchlistGeneral(_i26.WatchlistTable? watchlist) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistGeneral, [watchlist]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<int> removeWatchlist(int? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [id, type]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<Map<String, dynamic>?> getWatchlistById(int? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistById, [id, type]),
            returnValue: _i16.Future<Map<String, dynamic>?>.value(),
          )
          as _i16.Future<Map<String, dynamic>?>);

  @override
  _i16.Future<List<Map<String, dynamic>>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i16.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i17.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [GetOnTheAirTV].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTV extends _i1.Mock implements _i27.GetOnTheAirTV {
  MockGetOnTheAirTV() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TVRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TVRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);
}

/// A class which mocks [GetPopularTV].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTV extends _i1.Mock implements _i28.GetPopularTV {
  MockGetPopularTV() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TVRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TVRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);
}

/// A class which mocks [GetTopRatedTV].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTV extends _i1.Mock implements _i29.GetTopRatedTV {
  MockGetTopRatedTV() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TVRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TVRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);
}

/// A class which mocks [GetTVDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVDetail extends _i1.Mock implements _i6.GetTVDetail {
  MockGetTVDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TVRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TVRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, _i19.TVDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, _i19.TVDetail>>.value(
                  _FakeEither_0<_i17.Failure, _i19.TVDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, _i19.TVDetail>>);
}

/// A class which mocks [GetTVRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVRecommendations extends _i1.Mock
    implements _i7.GetTVRecommendations {
  MockGetTVRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TVRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TVRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);
}

/// A class which mocks [SearchTV].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTV extends _i1.Mock implements _i30.SearchTV {
  MockSearchTV() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TVRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TVRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>> execute(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.TV>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.TV>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i8.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.WatchlistRepository);

  @override
  _i16.Future<bool> execute(int? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id, type]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i9.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.WatchlistRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, String>> execute(
    _i31.Watchlist? watchlist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [watchlist]),
            returnValue: _i16.Future<_i2.Either<_i17.Failure, String>>.value(
              _FakeEither_0<_i17.Failure, String>(
                this,
                Invocation.method(#execute, [watchlist]),
              ),
            ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i10.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.WatchlistRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, String>> execute(
    _i31.Watchlist? watchlist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [watchlist]),
            returnValue: _i16.Future<_i2.Either<_i17.Failure, String>>.value(
              _FakeEither_0<_i17.Failure, String>(
                this,
                Invocation.method(#execute, [watchlist]),
              ),
            ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, String>>);
}

/// A class which mocks [TVDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVDetailBloc extends _i1.Mock implements _i11.TVDetailBloc {
  MockTVDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetTVDetail get getTVDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTVDetail),
            returnValue: _FakeGetTVDetail_4(
              this,
              Invocation.getter(#getTVDetail),
            ),
          )
          as _i6.GetTVDetail);

  @override
  _i7.GetTVRecommendations get getTVRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTVRecommendations),
            returnValue: _FakeGetTVRecommendations_5(
              this,
              Invocation.getter(#getTVRecommendations),
            ),
          )
          as _i7.GetTVRecommendations);

  @override
  _i8.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatus_6(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i8.GetWatchListStatus);

  @override
  _i9.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlist_7(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i9.SaveWatchlist);

  @override
  _i10.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlist_8(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i10.RemoveWatchlist);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i11.TVDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTVDetailState_9(this, Invocation.getter(#state)),
          )
          as _i11.TVDetailState);

  @override
  _i16.Stream<_i11.TVDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i11.TVDetailState>.empty(),
          )
          as _i16.Stream<_i11.TVDetailState>);

  @override
  void add(_i11.TVDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.TVDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.TVDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.TVDetailEvent>(
    _i32.EventHandler<E, _i11.TVDetailState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i11.TVDetailEvent, _i11.TVDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i11.TVDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i11.TVDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TVSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSearchBloc extends _i1.Mock implements _i33.TVSearchBloc {
  MockTVSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i33.TVSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i34.dummyValue<_i33.TVSearchState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i33.TVSearchState);

  @override
  _i16.Stream<_i33.TVSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i33.TVSearchState>.empty(),
          )
          as _i16.Stream<_i33.TVSearchState>);

  @override
  void add(_i33.TVSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i33.TVSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i33.TVSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i33.TVSearchEvent>(
    _i32.EventHandler<E, _i33.TVSearchState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i33.TVSearchEvent, _i33.TVSearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i33.TVSearchEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i33.TVSearchState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTVBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTVBloc extends _i1.Mock implements _i12.OnTheAirTVBloc {
  MockOnTheAirTVBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.OnTheAirTVState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnTheAirTVState_10(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.OnTheAirTVState);

  @override
  _i16.Stream<_i12.OnTheAirTVState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i12.OnTheAirTVState>.empty(),
          )
          as _i16.Stream<_i12.OnTheAirTVState>);

  @override
  void add(_i12.OnTheAirTVEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.OnTheAirTVEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i12.OnTheAirTVState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.OnTheAirTVEvent>(
    _i32.EventHandler<E, _i12.OnTheAirTVState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i12.OnTheAirTVEvent, _i12.OnTheAirTVState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i12.OnTheAirTVEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i12.OnTheAirTVState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTVBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTVBloc extends _i1.Mock implements _i13.PopularTVBloc {
  MockPopularTVBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i13.PopularTVState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTVState_11(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i13.PopularTVState);

  @override
  _i16.Stream<_i13.PopularTVState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i13.PopularTVState>.empty(),
          )
          as _i16.Stream<_i13.PopularTVState>);

  @override
  void add(_i13.PopularTVEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i13.PopularTVEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i13.PopularTVState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i13.PopularTVEvent>(
    _i32.EventHandler<E, _i13.PopularTVState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i13.PopularTVEvent, _i13.PopularTVState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i13.PopularTVEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i13.PopularTVState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTVBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTVBloc extends _i1.Mock implements _i14.TopRatedTVBloc {
  MockTopRatedTVBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.TopRatedTVState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTVState_12(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i14.TopRatedTVState);

  @override
  _i16.Stream<_i14.TopRatedTVState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i14.TopRatedTVState>.empty(),
          )
          as _i16.Stream<_i14.TopRatedTVState>);

  @override
  void add(_i14.TopRatedTVEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.TopRatedTVEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i14.TopRatedTVState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.TopRatedTVEvent>(
    _i32.EventHandler<E, _i14.TopRatedTVState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i14.TopRatedTVEvent, _i14.TopRatedTVState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i14.TopRatedTVEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i14.TopRatedTVState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i15.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i15.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i16.Future<String>.value(
              _i34.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<_i36.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i16.Future<_i36.Uint8List>.value(_i36.Uint8List(0)),
          )
          as _i16.Future<_i36.Uint8List>);

  @override
  _i16.Future<_i15.StreamedResponse> send(_i15.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i16.Future<_i15.StreamedResponse>.value(
              _FakeStreamedResponse_14(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i16.Future<_i15.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
