// Mocks generated by Mockito 5.4.6 from annotations
// in movie/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:convert' as _i35;
import 'dart:typed_data' as _i36;

import 'package:core/core.dart' as _i17;
import 'package:dartz/dartz.dart' as _i2;
import 'package:db/db.dart' as _i24;
import 'package:flutter_bloc/flutter_bloc.dart' as _i32;
import 'package:http/http.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i34;
import 'package:movie/data/datasources/movie_local_data_source.dart' as _i22;
import 'package:movie/data/datasources/movie_remote_data_source.dart' as _i20;
import 'package:movie/data/models/movie_detail_model.dart' as _i3;
import 'package:movie/data/models/movie_model.dart' as _i21;
import 'package:movie/data/models/movie_table.dart' as _i23;
import 'package:movie/domain/entities/movie.dart' as _i18;
import 'package:movie/domain/entities/movie_detail.dart' as _i19;
import 'package:movie/domain/repos/movie_repository.dart' as _i4;
import 'package:movie/domain/usecases/get_movie_detail.dart' as _i6;
import 'package:movie/domain/usecases/get_movie_recommendations.dart' as _i7;
import 'package:movie/domain/usecases/get_now_playing_movies.dart' as _i27;
import 'package:movie/domain/usecases/get_popular_movies.dart' as _i28;
import 'package:movie/domain/usecases/get_top_rated_movies.dart' as _i29;
import 'package:movie/domain/usecases/search_movies.dart' as _i30;
import 'package:movie/presentation/blocs/movie_detail_bloc.dart' as _i11;
import 'package:movie/presentation/blocs/movie_search_bloc.dart' as _i33;
import 'package:movie/presentation/blocs/now_playing_movies_bloc.dart' as _i12;
import 'package:movie/presentation/blocs/popular_movies_bloc.dart' as _i13;
import 'package:movie/presentation/blocs/top_rated_movies_bloc.dart' as _i14;
import 'package:sqflite/sqflite.dart' as _i25;
import 'package:watchlist/data/models/watchlist_table.dart' as _i26;
import 'package:watchlist/domain/entities/watchlist.dart' as _i31;
import 'package:watchlist/domain/repos/watchlist_repository.dart' as _i5;
import 'package:watchlist/domain/usecases/get_watchlist_status.dart' as _i8;
import 'package:watchlist/domain/usecases/remove_watchlist.dart' as _i10;
import 'package:watchlist/domain/usecases/save_watchlist.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieRepository_2 extends _i1.SmartFake
    implements _i4.MovieRepository {
  _FakeMovieRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistRepository_3 extends _i1.SmartFake
    implements _i5.WatchlistRepository {
  _FakeWatchlistRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieDetail_4 extends _i1.SmartFake
    implements _i6.GetMovieDetail {
  _FakeGetMovieDetail_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieRecommendations_5 extends _i1.SmartFake
    implements _i7.GetMovieRecommendations {
  _FakeGetMovieRecommendations_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatus_6 extends _i1.SmartFake
    implements _i8.GetWatchListStatus {
  _FakeGetWatchListStatus_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlist_7 extends _i1.SmartFake implements _i9.SaveWatchlist {
  _FakeSaveWatchlist_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlist_8 extends _i1.SmartFake
    implements _i10.RemoveWatchlist {
  _FakeRemoveWatchlist_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailState_9 extends _i1.SmartFake
    implements _i11.MovieDetailState {
  _FakeMovieDetailState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNowPlayingMoviesState_10 extends _i1.SmartFake
    implements _i12.NowPlayingMoviesState {
  _FakeNowPlayingMoviesState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularMoviesState_11 extends _i1.SmartFake
    implements _i13.PopularMoviesState {
  _FakePopularMoviesState_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedMoviesState_12 extends _i1.SmartFake
    implements _i14.TopRatedMoviesState {
  _FakeTopRatedMoviesState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_13 extends _i1.SmartFake implements _i15.Response {
  _FakeResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_14 extends _i1.SmartFake
    implements _i15.StreamedResponse {
  _FakeStreamedResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i4.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>
  getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, _i19.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, _i19.MovieDetail>>.value(
                  _FakeEither_0<_i17.Failure, _i19.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, _i19.MovieDetail>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>
  getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i20.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<List<_i21.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i16.Future<List<_i21.MovieModel>>.value(
              <_i21.MovieModel>[],
            ),
          )
          as _i16.Future<List<_i21.MovieModel>>);

  @override
  _i16.Future<List<_i21.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i16.Future<List<_i21.MovieModel>>.value(
              <_i21.MovieModel>[],
            ),
          )
          as _i16.Future<List<_i21.MovieModel>>);

  @override
  _i16.Future<List<_i21.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i16.Future<List<_i21.MovieModel>>.value(
              <_i21.MovieModel>[],
            ),
          )
          as _i16.Future<List<_i21.MovieModel>>);

  @override
  _i16.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i16.Future<_i3.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_1(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i16.Future<_i3.MovieDetailResponse>);

  @override
  _i16.Future<List<_i21.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i16.Future<List<_i21.MovieModel>>.value(
              <_i21.MovieModel>[],
            ),
          )
          as _i16.Future<List<_i21.MovieModel>>);

  @override
  _i16.Future<List<_i21.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i16.Future<List<_i21.MovieModel>>.value(
              <_i21.MovieModel>[],
            ),
          )
          as _i16.Future<List<_i21.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i22.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<void> cacheNowPlayingMovies(List<_i23.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheNowPlayingMovies, [movies]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<List<_i23.MovieTable>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedNowPlayingMovies, []),
            returnValue: _i16.Future<List<_i23.MovieTable>>.value(
              <_i23.MovieTable>[],
            ),
          )
          as _i16.Future<List<_i23.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i24.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i25.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i16.Future<_i25.Database?>.value(),
          )
          as _i16.Future<_i25.Database?>);

  @override
  _i16.Future<void> insertCacheTransaction(
    List<_i23.MovieTable>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i16.Future<List<Map<String, dynamic>>>);

  @override
  _i16.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<int> insertWatchlistGeneral(_i26.WatchlistTable? watchlist) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistGeneral, [watchlist]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<int> removeWatchlist(int? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [id, type]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<Map<String, dynamic>?> getWatchlistById(int? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistById, [id, type]),
            returnValue: _i16.Future<Map<String, dynamic>?>.value(),
          )
          as _i16.Future<Map<String, dynamic>?>);

  @override
  _i16.Future<List<Map<String, dynamic>>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i16.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i17.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [GetNowPlayingMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingMovies extends _i1.Mock
    implements _i27.GetNowPlayingMovies {
  MockGetNowPlayingMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovies extends _i1.Mock implements _i28.GetPopularMovies {
  MockGetPopularMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i29.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i6.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, _i19.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, _i19.MovieDetail>>.value(
                  _FakeEither_0<_i17.Failure, _i19.MovieDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, _i19.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i7.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [SearchMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovies extends _i1.Mock implements _i30.SearchMovies {
  MockSearchMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>.value(
                  _FakeEither_0<_i17.Failure, List<_i18.Movie>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i8.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.WatchlistRepository);

  @override
  _i16.Future<bool> execute(int? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id, type]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i9.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.WatchlistRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, String>> execute(
    _i31.Watchlist? watchlist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [watchlist]),
            returnValue: _i16.Future<_i2.Either<_i17.Failure, String>>.value(
              _FakeEither_0<_i17.Failure, String>(
                this,
                Invocation.method(#execute, [watchlist]),
              ),
            ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i10.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.WatchlistRepository);

  @override
  _i16.Future<_i2.Either<_i17.Failure, String>> execute(
    _i31.Watchlist? watchlist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [watchlist]),
            returnValue: _i16.Future<_i2.Either<_i17.Failure, String>>.value(
              _FakeEither_0<_i17.Failure, String>(
                this,
                Invocation.method(#execute, [watchlist]),
              ),
            ),
          )
          as _i16.Future<_i2.Either<_i17.Failure, String>>);
}

/// A class which mocks [MovieDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailBloc extends _i1.Mock implements _i11.MovieDetailBloc {
  MockMovieDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieDetail),
            returnValue: _FakeGetMovieDetail_4(
              this,
              Invocation.getter(#getMovieDetail),
            ),
          )
          as _i6.GetMovieDetail);

  @override
  _i7.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieRecommendations),
            returnValue: _FakeGetMovieRecommendations_5(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
          )
          as _i7.GetMovieRecommendations);

  @override
  _i8.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatus_6(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i8.GetWatchListStatus);

  @override
  _i9.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlist_7(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i9.SaveWatchlist);

  @override
  _i10.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlist_8(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i10.RemoveWatchlist);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i11.MovieDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailState_9(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i11.MovieDetailState);

  @override
  _i16.Stream<_i11.MovieDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i11.MovieDetailState>.empty(),
          )
          as _i16.Stream<_i11.MovieDetailState>);

  @override
  void add(_i11.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.MovieDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.MovieDetailEvent>(
    _i32.EventHandler<E, _i11.MovieDetailState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i11.MovieDetailEvent, _i11.MovieDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i11.MovieDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i11.MovieDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchBloc extends _i1.Mock implements _i33.MovieSearchBloc {
  MockMovieSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i33.MovieSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i34.dummyValue<_i33.MovieSearchState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i33.MovieSearchState);

  @override
  _i16.Stream<_i33.MovieSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i33.MovieSearchState>.empty(),
          )
          as _i16.Stream<_i33.MovieSearchState>);

  @override
  void add(_i33.MovieSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i33.MovieSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i33.MovieSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i33.MovieSearchEvent>(
    _i32.EventHandler<E, _i33.MovieSearchState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i33.MovieSearchEvent, _i33.MovieSearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i33.MovieSearchEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i33.MovieSearchState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NowPlayingMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNowPlayingMoviesBloc extends _i1.Mock
    implements _i12.NowPlayingMoviesBloc {
  MockNowPlayingMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.NowPlayingMoviesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNowPlayingMoviesState_10(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.NowPlayingMoviesState);

  @override
  _i16.Stream<_i12.NowPlayingMoviesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i12.NowPlayingMoviesState>.empty(),
          )
          as _i16.Stream<_i12.NowPlayingMoviesState>);

  @override
  void add(_i12.NowPlayingMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.NowPlayingMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i12.NowPlayingMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.NowPlayingMoviesEvent>(
    _i32.EventHandler<E, _i12.NowPlayingMoviesState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i12.NowPlayingMoviesEvent, _i12.NowPlayingMoviesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i12.NowPlayingMoviesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i12.NowPlayingMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesBloc extends _i1.Mock implements _i13.PopularMoviesBloc {
  MockPopularMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i13.PopularMoviesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularMoviesState_11(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i13.PopularMoviesState);

  @override
  _i16.Stream<_i13.PopularMoviesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i13.PopularMoviesState>.empty(),
          )
          as _i16.Stream<_i13.PopularMoviesState>);

  @override
  void add(_i13.PopularMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i13.PopularMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i13.PopularMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i13.PopularMoviesEvent>(
    _i32.EventHandler<E, _i13.PopularMoviesState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i13.PopularMoviesEvent, _i13.PopularMoviesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i13.PopularMoviesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i13.PopularMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedMoviesBloc extends _i1.Mock
    implements _i14.TopRatedMoviesBloc {
  MockTopRatedMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.TopRatedMoviesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedMoviesState_12(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i14.TopRatedMoviesState);

  @override
  _i16.Stream<_i14.TopRatedMoviesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i14.TopRatedMoviesState>.empty(),
          )
          as _i16.Stream<_i14.TopRatedMoviesState>);

  @override
  void add(_i14.TopRatedMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.TopRatedMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i14.TopRatedMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.TopRatedMoviesEvent>(
    _i32.EventHandler<E, _i14.TopRatedMoviesState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i14.TopRatedMoviesEvent, _i14.TopRatedMoviesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i14.TopRatedMoviesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i32.Change<_i14.TopRatedMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i15.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i15.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<_i15.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i35.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i15.Response>.value(
              _FakeResponse_13(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i15.Response>);

  @override
  _i16.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i16.Future<String>.value(
              _i34.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<_i36.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i16.Future<_i36.Uint8List>.value(_i36.Uint8List(0)),
          )
          as _i16.Future<_i36.Uint8List>);

  @override
  _i16.Future<_i15.StreamedResponse> send(_i15.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i16.Future<_i15.StreamedResponse>.value(
              _FakeStreamedResponse_14(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i16.Future<_i15.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
